/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { WorkService } from "../work.service";
import { WorkCreateInput } from "./WorkCreateInput";
import { WorkWhereInput } from "./WorkWhereInput";
import { WorkWhereUniqueInput } from "./WorkWhereUniqueInput";
import { WorkFindManyArgs } from "./WorkFindManyArgs";
import { WorkUpdateInput } from "./WorkUpdateInput";
import { Work } from "./Work";

export class WorkGrpcControllerBase {
  constructor(protected readonly service: WorkService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Work })
  @GrpcMethod("WorkService", "createWork")
  async createWork(@common.Body() data: WorkCreateInput): Promise<Work> {
    return await this.service.createWork({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Work] })
  @ApiNestedQuery(WorkFindManyArgs)
  @GrpcMethod("WorkService", "works")
  async works(@common.Req() request: Request): Promise<Work[]> {
    const args = plainToClass(WorkFindManyArgs, request.query);
    return this.service.works({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Work })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WorkService", "work")
  async work(
    @common.Param() params: WorkWhereUniqueInput
  ): Promise<Work | null> {
    const result = await this.service.work({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Work })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WorkService", "updateWork")
  async updateWork(
    @common.Param() params: WorkWhereUniqueInput,
    @common.Body() data: WorkUpdateInput
  ): Promise<Work | null> {
    try {
      return await this.service.updateWork({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Work })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WorkService", "deleteWork")
  async deleteWork(
    @common.Param() params: WorkWhereUniqueInput
  ): Promise<Work | null> {
    try {
      return await this.service.deleteWork({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
